version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      -"8000:8000"
    environment:
      - ENV_VAT_NAME=Value
    volumes:
      - ./:/app
    command: python main.py